# pip install -i https://test.pypi.org/simple/ Sheep==0.0.7
from sheep import page
page.create()
page.set_title('sheep??????')
page.set_icon('https://i.pinimg.com/564x/66/a0/6d/66a06d5f33a803738c7747618c94e4d8.jpg')
page.set_background(image='https://i.pinimg.com/736x/cf/92/99/cf9299fb011122c844c904e66c0833cf.jpg', image_repeat=False, image_size='cover')
page.add_font(src='https://fonts.googleapis.com/css?family=Roboto')
page.write(language='en', style='H1', content=f'I\'m updating this Sheep site built with Sheep and atm it\'s horrible anyways check out the code', link_text='code', url='https://github.com/AtlasL1/Sheep', new_tab=True, size='29px', font='Roboto', colour='yellow')
page.style_links(text_colour='yellow', hover_colour='orange', visited_colour='yellow', active_colour='')
page.add_button(text='link to code again but it\'s a button this time', onclick='alert(\'hideous repo with hideous code incoming\')', border='none', border_after='none', text_decoration='underline', text_decoration_style='wavy', text_decoration_thickness='2px', text_decoration_colour='orange', background_colour='yellow', text_decoration_after='underline', text_decoration_colour_after='yellow', text_decoration_style_after='wavy', text_decoration_thickness_after='2px', background_colour_after='orange', url='https://github.com/AtlasL1/Sheep', new_tab=True)
page.line_break(number='1')
page.add_image(path='https://i.pinimg.com/564x/d3/75/4d/d3754dadeed8a28dea4a423cc75b9cc7.jpg', alt_text='Closeup Sheep')
page.write(language='en', style='H2', content=f'The picture below is linked to the code (again)', font='Roboto', colour='yellow')
page.add_image(path='https://i.pinimg.com/564x/15/b0/f6/15b0f611bec878d513512c28cc9e3e7b.jpg', url='https://github.com/AtlasL1/Sheep', new_tab=True)
list1 = page.add_list(type='ordered')
list1.add_item(content='Guess what', font='Roboto', colour='orange', size='24px')
list1.add_item(content='Did you miss the link to the code', font='Roboto', colour='orange', size='24px')
list1.add_item(content='Pretty sure you did', font='Roboto', colour='orange', size='24px')
list1.add_item(content='I forgive you', font='Roboto', colour='orange', size='24px')
list1.add_item(content='Here\'s the link to le code', font='Roboto', colour='orange', size='24px', link_text='link to le code', url='https://github.com/AtlasL1/Sheep', new_tab=True)
list1.close_list()
list2 = page.add_list(type='unordered')
list2.add_item(content='Sharing is caring', font='Roboto', colour='gold', size='24px')
list2.add_item(content='I suffered and so should you', font='Roboto', colour='gold', size='24px')
list2.close_list()
page.write(language='en', style='H3', content='Anyways here\'s my Discord server for DEVS', font='Roboto', colour='yellow', link_text='DEVS', url='https://buc.developer.li', new_tab=True)
page.add_iframe(src='https://discord.com/widget?id=1112353759784341614&theme=dark', width='700', height='500')
page.write(language='en', style='H3', content='And one for my projectssssssss', font='Roboto', colour='yellow')
page.add_iframe(src='https://discord.com/widget?id=1154045009386025020&theme=dark', width='700', height='500')
page.line_break(1)
page.add_audio(src='https://www.fesliyanstudios.com/play-mp3/6630', type='mp3', autoplay=False)
page.add_blocked_text(text_style='H2', block_style='solid', text='blocked text yay', text_colour='yellow', block_colour='orange', font='Roboto', text_size='22px')
page.view_page()
